In [9]:
import pandas as pd

In [6]:
pd.__version__

'0.23.4'

In [6]:
df = pd.DataFrame({'nombre': ['Rick', 'Marty'], 'apellidos': ['Sanchez', 'Smith'], 'edad': [60, 14]})
df

  nombre apellidos  edad
0   Rick   Sanchez    60
1  Marty     Smith    14

In [8]:
df = pd.DataFrame([['Rick', 'Sanchez', 60], ['Marty', 'Smith', 14]], columns=['nombre', 'apellidos', 'edad'])
df

  nombre apellidos  edad
0   Rick   Sanchez    60
1  Marty     Smith    14

In [4]:
data = pd.read_csv("primary_results.csv")
data.head()

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
0,Alabama,AL,Autauga,1001.0,Democrat,Bernie Sanders,544,0.182
1,Alabama,AL,Autauga,1001.0,Democrat,Hillary Clinton,2387,0.800
2,Alabama,AL,Baldwin,1003.0,Democrat,Bernie Sanders,2694,0.329
3,Alabama,AL,Baldwin,1003.0,Democrat,Hillary Clinton,5290,0.647
4,Alabama,AL,Barbour,1005.0,Democrat,Bernie Sanders,222,0.078

In [13]:
data.tail(10)

,state,state_abbreviation,county,fips,party,candidate,votes,fraction_votes
24601,Wyoming,WY,Sweetwater-Carbon,95600026.0,Republican,Marco Rubio,28,0.315
24602,Wyoming,WY,Sweetwater-Carbon,95600026.0,Republican,Ted Cruz,45,0.506
24603,Wyoming,WY,Teton-Sublette,95600028.0,Republican,Donald Trump,21,0.525
24604,Wyoming,WY,Teton-Sublette,95600028.0,Republican,John Kasich,0,0.000
24605,Wyoming,WY,Teton-Sublette,95600028.0,Republican,Marco Rubio,19,0.475
24606,Wyoming,WY,Teton-Sublette,95600028.0,Republican,Ted Cruz,0,0.000
24607,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Donald Trump,0,0.000
24608,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,John Kasich,0,0.000
24609,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Marco Rubio,0,0.000
24610,Wyoming,WY,Uinta-Lincoln,95600027.0,Republican,Ted Cruz,53,1.000

In [14]:
data.describe()

               fips          votes  fraction_votes
count  2.451100e+04   24611.000000    24611.000000
mean   2.667152e+07    2306.252773        0.304524
std    4.200978e+07    9861.183572        0.231401
min    1.001000e+03       0.000000        0.000000
25%    2.109100e+04      68.000000        0.094000
50%    4.208100e+04     358.000000        0.273000
75%    9.090012e+07    1375.000000        0.479000
max    9.560004e+07  590502.000000        1.000000

In [15]:
data.dtypes

state                  object
state_abbreviation     object
county                 object
fips                  float64
party                  object
candidate              object
votes                   int64
fraction_votes        float64
dtype: object

In [16]:
data.index

RangeIndex(start=0, stop=24611, step=1)

In [18]:
data2 = data.set_index("county")
data2

,state,state_abbreviation,fips,party,candidate,votes,fraction_votes
county,,,,,,,
Autauga,Alabama,AL,1001.0,Democrat,Bernie Sanders,544,0.182
Autauga,Alabama,AL,1001.0,Democrat,Hillary Clinton,2387,0.800
Baldwin,Alabama,AL,1003.0,Democrat,Bernie Sanders,2694,0.329
Baldwin,Alabama,AL,1003.0,Democrat,Hillary Clinton,5290,0.647
Barbour,Alabama,AL,1005.0,Democrat,Bernie Sanders,222,0.078
Barbour,Alabama,AL,1005.0,Democrat,Hillary Clinton,2567,0.906
Bibb,Alabama,AL,1007.0,Democrat,Bernie Sanders,246,0.197
Bibb,Alabama,AL,1007.0,Democrat,Hillary Clinton,942,0.755
Blount,Alabama,AL,1009.0,Democrat,Bernie Sanders,395,0.386
Blount,Alabama,AL,1009.0,Democrat,Hillary Clinton,564,0.551
Bullock,Alabama,AL,1011.0,Democrat,Bernie Sanders,178,0.066
Bullock,Alabama,AL,1011.0,Democrat,Hillary Clinton,2451,0.913
Butler,Alabama,AL,1013.0,Democrat,Bernie Sanders,156,0.065
Butler,Alabama,AL,1013.0,Democrat,Hillary Clinton,2196,0.921
Calhoun,Alabama,AL,1015.0,Democrat,Bernie Sanders,1425,0.218
Calhoun,Alabama,AL,1015.0,Democrat,Hillary Clinton,5011,0.765
Chambers,Alabama,AL,1017.0,Democrat,Bernie Sanders,312,0.095
Chambers,Alabama,AL,1017.0,Democrat,Hillary Clinton,2899,0.886
Cherokee,Alabama,AL,1019.0,Democrat,Bernie Sanders,268,0.249
Cherokee,Alabama,AL,1019.0,Democrat,Hillary Clinton,712,0.661
Chilton,Alabama,AL,1021.0,Democrat,Bernie Sanders,289,0.246
Chilton,Alabama,AL,1021.0,Democrat,Hillary Clinton,860,0.731
Choctaw,Alabama,AL,1023.0,Democrat,Bernie Sanders,273,0.124
Choctaw,Alabama,AL,1023.0,Democrat,Hillary Clinton,1772,0.802
Clarke,Alabama,AL,1025.0,Democrat,Bernie Sanders,213,0.063
Clarke,Alabama,AL,1025.0,Democrat,Hillary Clinton,3148,0.930
Clay,Alabama,AL,1027.0,Democrat,Bernie Sanders,135,0.137
Clay,Alabama,AL,1027.0,Democrat,Hillary Clinton,807,0.818
Cleburne,Alabama,AL,1029.0,Democrat,Bernie Sanders,72,0.238
Cleburne,Alabama,AL,1029.0,Democrat,Hillary Clinton,221,0.732
...,...,...,...,...,...,...,...
Fremont-Park,Wyoming,WY,95600029.0,Republican,Marco Rubio,0,0.000
Fremont-Park,Wyoming,WY,95600029.0,Republican,Ted Cruz,64,0.660
Goshen-Platte,Wyoming,WY,95600035.0,Republican,Donald Trump,0,0.000
Goshen-Platte,Wyoming,WY,95600035.0,Republican,John Kasich,0,0.000
Goshen-Platte,Wyoming,WY,95600035.0,Republican,Marco Rubio,0,0.000
Goshen-Platte,Wyoming,WY,95600035.0,Republican,Ted Cruz,83,1.000
Hot Springs-Washakie,Wyoming,WY,95600030.0,Republican,Donald Trump,0,0.000
Hot Springs-Washakie,Wyoming,WY,95600030.0,Republican,John Kasich,0,0.000
Hot Springs-Washakie,Wyoming,WY,95600030.0,Republican,Marco Rubio,0,0.000
Hot Springs-Washakie,Wyoming,WY,95600030.0,Republican,Ted Cruz,43,1.000
Laramie,Wyoming,WY,95600036.0,Republican,Donald Trump,0,0.000
Laramie,Wyoming,WY,95600036.0,Republican,John Kasich,0,0.000
Laramie,Wyoming,WY,95600036.0,Republican,Marco Rubio,38,0.176
Laramie,Wyoming,WY,95600036.0,Republican,Ted Cruz,141,0.653
Sheridan-Big Horn,Wyoming,WY,95600031.0,Republican,Donald Trump,0,0.000
Sheridan-Big Horn,Wyoming,WY,95600031.0,Republican,John Kasich,0,0.000
Sheridan-Big Horn,Wyoming,WY,95600031.0,Republican,Marco Rubio,30,0.400
Sheridan-Big Horn,Wyoming,WY,95600031.0,Republican,Ted Cruz,45,0.600
Sweetwater-Carbon,Wyoming,WY,95600026.0,Republican,Donald Trump,16,0.180
Sweetwater-Carbon,Wyoming,WY,95600026.0,Republican,John Kasich,0,0.000
Sweetwater-Carbon,Wyoming,WY,95600026.0,Republican,Marco Rubio,28,0.315
Sweetwater-Carbon,Wyoming,WY,95600026.0,Republican,Ted Cruz,45,0.506
Teton-Sublette,Wyoming,WY,95600028.0,Republican,Donald Trump,21,0.525
Teton-Sublette,Wyoming,WY,95600028.0,Republican,John Kasich,0,0.000
Teton-Sublette,Wyoming,WY,95600028.0,Republican,Marco Rubio,19,0.475
Teton-Sublette,Wyoming,WY,95600028.0,Republican,Ted Cruz,0,0.000
Uinta-Lincoln,Wyoming,WY,95600027.0,Republican,Donald Trump,0,0.000
Uinta-Lincoln,Wyoming,WY,95600027.0,Republican,John Kasich,0,0.000
Uinta-Lincoln,Wyoming,WY,95600027.0,Republican,Marco Rubio,0,0.000
Uinta-Lincoln,Wyoming,WY,95600027.0,Republican,Ted Cruz,53,1.000

Seek in column index

In [20]:
data2.loc["Laramie"]

,state,state_abbreviation,fips,party,candidate,votes,fraction_votes
county,,,,,,,
Laramie,Wyoming,WY,56021.0,Democrat,Bernie Sanders,25,0.490
Laramie,Wyoming,WY,56021.0,Democrat,Hillary Clinton,26,0.510
Laramie,Wyoming,WY,95600036.0,Republican,Donald Trump,0,0.000
Laramie,Wyoming,WY,95600036.0,Republican,John Kasich,0,0.000
Laramie,Wyoming,WY,95600036.0,Republican,Marco Rubio,38,0.176
Laramie,Wyoming,WY,95600036.0,Republican,Ted Cruz,141,0.653

In [ ]:
Seek specific row in index

In [22]:
data2.iloc[2]

state                        Alabama
state_abbreviation                AL
fips                            1003
party                       Democrat
candidate             Bernie Sanders
votes                           2694
fraction_votes                 0.329
Name: Baldwin, dtype: object

In [24]:
data2["state"]

county
Autauga                 Alabama
Autauga                 Alabama
Baldwin                 Alabama
Baldwin                 Alabama
Barbour                 Alabama
Barbour                 Alabama
Bibb                    Alabama
Bibb                    Alabama
Blount                  Alabama
Blount                  Alabama
Bullock                 Alabama
Bullock                 Alabama
Butler                  Alabama
Butler                  Alabama
Calhoun                 Alabama
Calhoun                 Alabama
Chambers                Alabama
Chambers                Alabama
Cherokee                Alabama
Cherokee                Alabama
Chilton                 Alabama
Chilton                 Alabama
Choctaw                 Alabama
Choctaw                 Alabama
Clarke                  Alabama
Clarke                  Alabama
Clay                    Alabama
Clay                    Alabama
Cleburne                Alabama
Cleburne                Alabama
                         ...
Fremont-Park            Wyoming
Fremont-Park            Wyoming
Goshen-Platte           Wyoming
Goshen-Platte           Wyoming
Goshen-Platte           Wyoming
Goshen-Platte           Wyoming
Hot Springs-Washakie    Wyoming
Hot Springs-Washakie    Wyoming
Hot Springs-Washakie    Wyoming
Hot Springs-Washakie    Wyoming
Laramie                 Wyoming
Laramie                 Wyoming
Laramie                 Wyoming
Laramie                 Wyoming
Sheridan-Big Horn       Wyoming
Sheridan-Big Horn       Wyoming
Sheridan-Big Horn       Wyoming
Sheridan-Big Horn       Wyoming
Sweetwater-Carbon       Wyoming
Sweetwater-Carbon       Wyoming
Sweetwater-Carbon       Wyoming
Sweetwater-Carbon       Wyoming
Teton-Sublette          Wyoming
Teton-Sublette          Wyoming
Teton-Sublette          Wyoming
Teton-Sublette          Wyoming
Uinta-Lincoln           Wyoming
Uinta-Lincoln           Wyoming
Uinta-Lincoln           Wyoming
Uinta-Lincoln           Wyoming
Name: state, Length: 24611, dtype: object

In [25]:
data2["new_column"] = 3

In [26]:
data2.head()

,state,state_abbreviation,fips,party,candidate,votes,fraction_votes,new_column
county,,,,,,,,
Autauga,Alabama,AL,1001.0,Democrat,Bernie Sanders,544,0.182,3
Autauga,Alabama,AL,1001.0,Democrat,Hillary Clinton,2387,0.800,3
Baldwin,Alabama,AL,1003.0,Democrat,Bernie Sanders,2694,0.329,3
Baldwin,Alabama,AL,1003.0,Democrat,Hillary Clinton,5290,0.647,3
Barbour,Alabama,AL,1005.0,Democrat,Bernie Sanders,222,0.078,3

Filtering for values in a column

In [27]:
data2[data2.votes> 500000]

,state,state_abbreviation,fips,party,candidate,votes,fraction_votes,new_column
county,,,,,,,,
Los Angeles,California,CA,6037.0,Democrat,Hillary Clinton,590502,0.57,3

Filtering with 2 columns

In [28]:
data2[(data2.party == "Democrat") & (data2.votes >200000)]

,state,state_abbreviation,fips,party,candidate,votes,fraction_votes,new_column
county,,,,,,,,
Los Angeles,California,CA,6037.0,Democrat,Bernie Sanders,434656,0.420,3
Los Angeles,California,CA,6037.0,Democrat,Hillary Clinton,590502,0.570,3
Chicago,Illinois,IL,91700103.0,Democrat,Bernie Sanders,311225,0.454,3
Chicago,Illinois,IL,91700103.0,Democrat,Hillary Clinton,366954,0.536,3
Cook Suburbs,Illinois,IL,91700104.0,Democrat,Bernie Sanders,212428,0.457,3
Cook Suburbs,Illinois,IL,91700104.0,Democrat,Hillary Clinton,249217,0.536,3
Philadelphia,Pennsylvania,PA,42101.0,Democrat,Hillary Clinton,212785,0.626,3

In [61]:
county1 = "Chicago"
county1
numvotes = 5000
#data2[data2.votes > @numvotes]
data2.query("votes > @numvotes")

TypeError: 'str' object is not callable